# Generated by Django 4.1 on 2022-08-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tokenvalidation_email_tokenvalidation_timetried_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
