# Generated by Django 4.1 on 2022-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='retaurant_admin',
            field=models.BooleanField(default=True),
        ),
    ]
